import { Repository } from 'typeorm';
import { Campaign } from '../entities/campaign.entity';
import { MarketingContent } from '../entities/marketing-content.entity';
import { AvatarVideo } from '../entities/avatar-video.entity';
import { AdvertisingDocument } from '../entities/advertising-document.entity';
import { DemographicSegment } from '../entities/demographic-segment.entity';
import { CampaignPerformance } from '../entities/campaign-performance.entity';
import { GlobalMarketingConfig } from '../entities/global-marketing-config.entity';
import { ContentGenerationService } from './content-generation.service';
import { VideoAvatarService } from './video-avatar.service';
import { QuantumAdvertisingService } from './quantum-advertising.service';
import { MarketingAutomationService } from './marketing-automation.service';
import { DemographicAnalysisService } from './demographic-analysis.service';
import { GlobalizationService } from './globalization.service';
import { CampaignAnalyticsService } from './campaign-analytics.service';
export declare class AISalesMarketingService {
    private campaignRepository;
    private marketingContentRepository;
    private avatarVideoRepository;
    private advertisingDocumentRepository;
    private demographicSegmentRepository;
    private campaignPerformanceRepository;
    private globalMarketingConfigRepository;
    private contentGenerationService;
    private videoAvatarService;
    private quantumAdvertisingService;
    private marketingAutomationService;
    private demographicAnalysisService;
    private globalizationService;
    private campaignAnalyticsService;
    private readonly logger;
    constructor(campaignRepository: Repository<Campaign>, marketingContentRepository: Repository<MarketingContent>, avatarVideoRepository: Repository<AvatarVideo>, advertisingDocumentRepository: Repository<AdvertisingDocument>, demographicSegmentRepository: Repository<DemographicSegment>, campaignPerformanceRepository: Repository<CampaignPerformance>, globalMarketingConfigRepository: Repository<GlobalMarketingConfig>, contentGenerationService: ContentGenerationService, videoAvatarService: VideoAvatarService, quantumAdvertisingService: QuantumAdvertisingService, marketingAutomationService: MarketingAutomationService, demographicAnalysisService: DemographicAnalysisService, globalizationService: GlobalizationService, campaignAnalyticsService: CampaignAnalyticsService);
    generateAIContent(contentRequest: any): Promise<any>;
    createAvatarVideo(videoRequest: any): Promise<any>;
    createQuantumAdvertisingDocuments(adRequest: any): Promise<any>;
    getMarketingCampaigns(filters: any): Promise<any>;
    analyzeDemographicsAndBehavior(analysisRequest: any): Promise<any>;
    getSupportedLanguages(): Promise<any>;
    getSupportedPaymentMethods(): Promise<any>;
    getCampaignAnalytics(filters: any): Promise<any>;
    createCampaign(campaignData: any): Promise<Campaign>;
    updateCampaign(id: string, updateData: any): Promise<Campaign>;
    deleteCampaign(id: string): Promise<void>;
    getCampaignById(id: string): Promise<Campaign>;
    trackCampaignPerformance(campaignId: string, performanceData: any): Promise<CampaignPerformance>;
    getGlobalMarketingConfig(): Promise<GlobalMarketingConfig[]>;
    updateGlobalMarketingConfig(configData: any): Promise<GlobalMarketingConfig>;
    getServiceStatus(): Promise<any>;
}
//# sourceMappingURL=ai-sales-marketing.service.d.ts.map