import { DataSource } from 'typeorm';
import { OrganizationService } from './organization.service';
import { DepartmentService } from './department.service';
import { PositionService } from './position.service';
import { Employee, CreateEmployeeRequest, ServiceResponse, DigitalTwinAnalysis, DNAAnalysis, QuantumConsciousness, MultidimensionalPersonality, EnergeticSignature, SoulPurposeAlignment, CosmicCareerPath, TranscendentWorkExperience } from '../types';
import { UUID } from 'crypto';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { CacheService } from '../../../core/services/cache.service';
import { AuditService } from '../../../core/services/audit.service';
import { AIService } from '../../../core/services/ai.service';
import { MLService } from '../../../core/services/ml.service';
import { NLPService } from '../../../core/services/nlp.service';
import { Industry5Service } from '../../../core/services/industry5.service';
import { QuantumAnalyticsService } from '../../../core/services/quantum-analytics.service';
import { NeuroInterfaceService } from '../../../core/services/neuro-interface.service';
import { BlockchainService } from '../../../core/services/blockchain.service';
import { MetaverseService } from '../../../core/services/metaverse.service';
import { DigitalTwinService } from '../../../core/services/digital-twin.service';
import { EdgeComputingService } from '../../../core/services/edge-computing.service';
import { BioMetricsService } from '../../../core/services/biometrics.service';
import { HyperPersonalizationEngine } from '../../../core/services/hyper-personalization.service';
import { DNAAnalysisService } from '../../../core/services/dna-analysis.service';
import { QuantumConsciousnessService } from '../../../core/services/quantum-consciousness.service';
import { MultidimensionalAnalysisService } from '../../../core/services/multidimensional-analysis.service';
import { EnergeticResonanceService } from '../../../core/services/energetic-resonance.service';
import { SoulPurposeService } from '../../../core/services/soul-purpose.service';
import { CosmicAlignmentService } from '../../../core/services/cosmic-alignment.service';
import { TranscendenceService } from '../../../core/services/transcendence.service';
import { HolisticWellbeingService } from '../../../core/services/holistic-wellbeing.service';
export declare class EmployeeService {
    private dataSource;
    private organizationService;
    private departmentService;
    private positionService;
    private eventEmitter;
    private cacheService;
    private auditService;
    private aiService;
    private mlService;
    private nlpService;
    private industry5Service;
    private quantumAnalytics;
    private neuroInterface;
    private blockchain;
    private metaverse;
    private digitalTwin;
    private edgeComputing;
    private bioMetrics;
    private hyperPersonalization;
    private dnaAnalysis;
    private quantumConsciousness;
    private multidimensionalAnalysis;
    private energeticResonance;
    private soulPurpose;
    private cosmicAlignment;
    private transcendence;
    private holisticWellbeing;
    private readonly logger;
    private readonly employeeModel;
    constructor(dataSource: DataSource, organizationService: OrganizationService, departmentService: DepartmentService, positionService: PositionService, eventEmitter: EventEmitter2, cacheService: CacheService, auditService: AuditService, aiService: AIService, mlService: MLService, nlpService: NLPService, industry5Service: Industry5Service, quantumAnalytics: QuantumAnalyticsService, neuroInterface: NeuroInterfaceService, blockchain: BlockchainService, metaverse: MetaverseService, digitalTwin: DigitalTwinService, edgeComputing: EdgeComputingService, bioMetrics: BioMetricsService, hyperPersonalization: HyperPersonalizationEngine, dnaAnalysis: DNAAnalysisService, quantumConsciousness: QuantumConsciousnessService, multidimensionalAnalysis: MultidimensionalAnalysisService, energeticResonance: EnergeticResonanceService, soulPurpose: SoulPurposeService, cosmicAlignment: CosmicAlignmentService, transcendence: TranscendenceService, holisticWellbeing: HolisticWellbeingService);
    createEmployee(organizationId: UUID, data: CreateEmployeeRequest, userId: UUID): Promise<ServiceResponse<Employee & {
        quantumConsciousness?: QuantumConsciousness;
        dnaAnalysis?: DNAAnalysis;
        multidimensionalPersonality?: MultidimensionalPersonality;
        energeticSignature?: EnergeticSignature;
        soulPurposeAlignment?: SoulPurposeAlignment;
        cosmicCareerPath?: CosmicCareerPath;
        digitalTwinConsciousness?: DigitalTwinAnalysis;
        transcendentWorkProfile?: TranscendentWorkExperience;
    }>>;
    healthCheck(): Promise<ServiceResponse<any>>;
    private generateQuantumEmployeeNumber;
    private getOrganizationQuantumCode;
}
//# sourceMappingURL=employee.service.d.ts.map