import { DataSource } from 'typeorm';
import { OrganizationService } from './organization.service';
import { DepartmentService } from './department.service';
import { Position, CreatePositionRequest, PositionAnalytics, CareerPath, PositionBenchmark, ServiceResponse, QuantumAnalytics, NeuroFeedbackData, BiometricInsights, BlockchainVerification, VRTrainingModule, ARWorkspaceOptimization, DigitalTwinAnalysis, HyperPersonalization } from '../types';
import { UUID } from 'crypto';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { CacheService } from '../../../core/services/cache.service';
import { AuditService } from '../../../core/services/audit.service';
import { AIService } from '../../../core/services/ai.service';
import { MLService } from '../../../core/services/ml.service';
import { NLPService } from '../../../core/services/nlp.service';
import { Industry5Service } from '../../../core/services/industry5.service';
import { QuantumAnalyticsService } from '../../../core/services/quantum-analytics.service';
import { NeuroInterfaceService } from '../../../core/services/neuro-interface.service';
import { BlockchainService } from '../../../core/services/blockchain.service';
import { MetaverseService } from '../../../core/services/metaverse.service';
import { DigitalTwinService } from '../../../core/services/digital-twin.service';
import { EdgeComputingService } from '../../../core/services/edge-computing.service';
import { BioMetricsService } from '../../../core/services/biometrics.service';
import { HyperPersonalizationEngine } from '../../../core/services/hyper-personalization.service';
export declare class PositionService {
    private dataSource;
    private organizationService;
    private departmentService;
    private eventEmitter;
    private cacheService;
    private auditService;
    private aiService;
    private mlService;
    private nlpService;
    private industry5Service;
    private quantumAnalytics;
    private neuroInterface;
    private blockchain;
    private metaverse;
    private digitalTwin;
    private edgeComputing;
    private bioMetrics;
    private hyperPersonalization;
    private readonly logger;
    private readonly positionModel;
    constructor(dataSource: DataSource, organizationService: OrganizationService, departmentService: DepartmentService, eventEmitter: EventEmitter2, cacheService: CacheService, auditService: AuditService, aiService: AIService, mlService: MLService, nlpService: NLPService, industry5Service: Industry5Service, quantumAnalytics: QuantumAnalyticsService, neuroInterface: NeuroInterfaceService, blockchain: BlockchainService, metaverse: MetaverseService, digitalTwin: DigitalTwinService, edgeComputing: EdgeComputingService, bioMetrics: BioMetricsService, hyperPersonalization: HyperPersonalizationEngine);
    createPosition(organizationId: UUID, data: CreatePositionRequest, userId: UUID): Promise<ServiceResponse<Position & {
        quantumInsights?: QuantumAnalytics;
        digitalTwin?: DigitalTwinAnalysis;
        blockchainVerification?: BlockchainVerification;
        metaverseWorkspace?: VRTrainingModule;
    }>>;
    getPositionQuantumAnalytics(positionId: UUID): Promise<ServiceResponse<PositionAnalytics & {
        quantumInsights: QuantumAnalytics;
        neuroFeedback: NeuroFeedbackData;
        biometricAnalysis: BiometricInsights;
        digitalTwinPredictions: DigitalTwinAnalysis;
        metaversePerformance: any;
        blockchainAuditTrail: BlockchainVerification[];
        hyperPersonalizedRecommendations: HyperPersonalization;
    }>>;
    getQuantumCareerPaths(organizationId: UUID, fromPositionId?: UUID): Promise<ServiceResponse<CareerPath[] & {
        quantumOpportunities: any[];
        metaverseTrainingPaths: VRTrainingModule[];
        neuroOptimizedLearning: any[];
        blockchainCertifiedSkills: any[];
        digitalTwinSimulations: any[];
    }>>;
    getQuantumSuccessionPlan(positionId: UUID): Promise<ServiceResponse<any>>;
    getQuantumSkillsInventory(organizationId: UUID): Promise<ServiceResponse<any>>;
    optimizeMetaverseWorkspace(positionId: UUID): Promise<ServiceResponse<ARWorkspaceOptimization>>;
    getQuantumPositionBenchmark(positionId: UUID): Promise<ServiceResponse<PositionBenchmark & {
        quantumMarketAnalysis: any;
        globalTalentIntelligence: any;
        industryDisruptionFactor: number;
        futureValuePrediction: any;
        competitivePositioning: any;
    }>>;
    autonomousPositionOptimization(positionId: UUID, userId: UUID): Promise<ServiceResponse<any>>;
    private calculateRevolutionaryScore;
    private predictIndustryDisruptions;
    private predictFutureSkills;
    private generateEmergencySuccessionProtocol;
    private setupContinuousSuccessionMonitoring;
    private predictDisruptionSkillNeeds;
    private identifyEmergentSkillsTrends;
    private analyzeSkillsROI;
    private analyzeCompetitiveSkills;
    private createAdaptiveWorkspaceEnvironments;
    private integrateHolisticWellbeing;
    private analyzeCompetitivePositioning;
    private calculateQuantumCompetitiveAdvantage;
    private identifyEmergentMarketOpportunities;
    private executeQuantumOptimization;
    private optimizeQuantumSkills;
    private enhanceMetaverseWorkspace;
    private integrateNeuroFeedback;
    private upgradeBlockchainVerification;
    private categorizeOptimizations;
    private predictOptimizationImpact;
    healthCheck(): Promise<ServiceResponse<any>>;
    private calculateSystemRevolutionaryScore;
}
//# sourceMappingURL=position.service.d.ts.map