// ===========================================
// REQUEST/RESPONSE TYPES FOR MAINTENANCE OPERATIONS
// Industry 5.0 ERP Backend System
// ===========================================

import { 
  Priority, 
  MaintenanceLevel, 
  FailureSeverity,
  MaintenanceMetrics,
  WorkOrder,
  AIMaintenanceInsights
} from './index';

// ===========================================
// AI-POWERED PREDICTIVE MAINTENANCE
// ===========================================

export interface MaintenanceSensorConfiguration {
  sensorId: string;
  sensorType: string;
  location: string;
  parameters: string[];
  samplingRate: number;
  thresholds: Record<string, number>;
}

export interface PredictionParameter {
  algorithm: string;
  timeHorizon: number; // in hours
  confidenceThreshold: number;
  features: string[];
  modelVersion: string;
}

export interface RemainingUsefulLifeParameter {
  degradationModel: string;
  operatingConditions: Record<string, number>;
  maintenanceHistory: string[];
  usagePattern: string;
}

export interface DegradationParameter {
  degradationType: string;
  monitoringPoints: string[];
  trendAnalysisWindow: number;
  seasonalityFactors: string[];
}

export interface MaintenanceWindowParameter {
  availabilityConstraints: Record<string, any>;
  resourceConstraints: string[];
  costOptimization: boolean;
  productionImpact: boolean;
}

export interface RiskAssessmentParameter {
  riskModel: string;
  impactFactors: string[];
  probabilityFactors: string[];
  businessImpactWeights: Record<string, number>;
}

export interface WorkOrderParameter {
  autoGeneration: boolean;
  assignmentRules: Record<string, any>;
  approvalWorkflow: string[];
  schedulingConstraints: Record<string, any>;
}

export interface AIPoweredPredictiveMaintenanceRequest {
  sensorConfiguration: MaintenanceSensorConfiguration[];
  predictionParameters: PredictionParameter[];
  rulParameters: RemainingUsefulLifeParameter[];
  degradationParameters: DegradationParameter[];
  windowParameters: MaintenanceWindowParameter[];
  riskParameters: RiskAssessmentParameter[];
  workOrderParameters: WorkOrderParameter[];
}

export interface FusedMaintenanceSensorData {
  fusionId: string;
  sensors: string[];
  correlationMatrix: number[][];
  fusedSignals: Record<string, number[]>;
  reliability: number;
  timestamp: Date;
}

export interface FailurePrediction {
  predictionId: string;
  equipmentId: string;
  failureType: string;
  probability: number;
  timeToFailure: number;
  severity: FailureSeverity;
  confidence: number;
  features: Record<string, number>;
}

export interface RemainingUsefulLifeEstimation {
  estimationId: string;
  equipmentId: string;
  remainingHours: number;
  confidenceInterval: [number, number];
  degradationRate: number;
  factors: Record<string, number>;
}

export interface DegradationPattern {
  patternId: string;
  patternType: string;
  trendDirection: 'increasing' | 'decreasing' | 'stable' | 'cyclic';
  magnitude: number;
  velocity: number;
  acceleration: number;
  seasonality: Record<string, any>;
}

export interface OptimizedMaintenanceWindow {
  windowId: string;
  startTime: Date;
  endTime: Date;
  duration: number;
  cost: number;
  resourceUtilization: Record<string, number>;
  riskLevel: string;
}

export interface MaintenanceRiskAssessment {
  assessmentId: string;
  overallRisk: number;
  riskCategories: Record<string, number>;
  criticalFactors: string[];
  mitigationRecommendations: string[];
}

export interface GeneratedWorkOrder {
  workOrderId: string;
  generatedFrom: string;
  autoGenerated: boolean;
  priority: Priority;
  scheduledDate: Date;
  estimatedDuration: number;
  estimatedCost: number;
  requiredResources: string[];
}

export interface MaintenanceInsight {
  insightId: string;
  category: string;
  description: string;
  impact: string;
  actionable: boolean;
  recommendedActions: string[];
  confidence: number;
}

export interface MaintenanceCostOptimization {
  optimizationId: string;
  potentialSavings: number;
  costBreakdown: Record<string, number>;
  recommendations: string[];
  implementation: string[];
}

export interface MaintenanceLearningPlan {
  planId: string;
  learningObjectives: string[];
  dataRequirements: string[];
  modelUpdates: string[];
  feedbackMechanisms: string[];
}

export interface AIPoweredPredictiveMaintenanceResult {
  predictionId: string;
  predictionTimestamp: Date;
  originalRequest: AIPoweredPredictiveMaintenanceRequest;
  sensorDataFusion: FusedMaintenanceSensorData;
  failurePrediction: FailurePrediction[];
  rulEstimation: RemainingUsefulLifeEstimation[];
  degradationAnalysis: DegradationPattern[];
  windowOptimization: OptimizedMaintenanceWindow[];
  riskAssessment: MaintenanceRiskAssessment[];
  workOrderGeneration: GeneratedWorkOrder[];
  predictiveInsights: MaintenanceInsight[];
  costOptimization: MaintenanceCostOptimization;
  continuousLearning: MaintenanceLearningPlan;
}

// ===========================================
// IOT EQUIPMENT MONITORING
// ===========================================

export interface IoTSensorConfiguration {
  sensorId: string;
  protocol: string;
  endpoint: string;
  dataFormat: string;
  encryption: boolean;
  authentication: Record<string, any>;
}

export interface DataProcessingParameter {
  streamProcessing: boolean;
  batchSize: number;
  aggregationWindow: number;
  filteringRules: string[];
  qualityChecks: string[];
}

export interface EquipmentHealthParameter {
  healthMetrics: string[];
  scoringAlgorithm: string;
  thresholds: Record<string, number>;
  alertLevels: Record<string, any>;
}

export interface ConditionBasedMaintenanceParameter {
  triggerConditions: Record<string, any>;
  escalationRules: string[];
  responseTime: number;
  actionTypes: string[];
}

export interface TrendAnalysisParameter {
  analysisWindow: number;
  trendDetectionAlgorithm: string;
  seasonalAdjustment: boolean;
  outlierHandling: string;
}

export interface AnomalyDetectionParameter {
  algorithm: string;
  sensitivityLevel: number;
  baselineWindow: number;
  adaptiveThresholds: boolean;
}

export interface DiagnosticsParameter {
  diagnosticModels: string[];
  failureModes: string[];
  expertRules: Record<string, any>;
  uncertaintyHandling: string;
}

export interface RealTimeIoTEquipmentMonitoringRequest {
  sensorConfiguration: IoTSensorConfiguration[];
  processingParameters: DataProcessingParameter[];
  healthParameters: EquipmentHealthParameter[];
  cbmParameters: ConditionBasedMaintenanceParameter[];
  trendParameters: TrendAnalysisParameter[];
  anomalyParameters: AnomalyDetectionParameter[];
  diagnosticsParameters: DiagnosticsParameter[];
}

export interface DeployedMaintenanceIoTNetwork {
  networkId: string;
  deployedSensors: number;
  networkTopology: string;
  communicationProtocols: string[];
  dataThroughput: number;
  latency: number;
  reliability: number;
}

export interface ProcessedMaintenanceDataStream {
  streamId: string;
  dataPoints: number;
  processingRate: number;
  dataQuality: number;
  anomaliesDetected: number;
  trends: string[];
}

export interface EquipmentHealthMetrics {
  equipmentId: string;
  overallHealthScore: number;
  componentScores: Record<string, number>;
  riskIndicators: string[];
  performanceIndex: number;
  degradationRate: number;
}

export interface TriggeredMaintenanceActions {
  actionId: string;
  triggerType: string;
  equipmentId: string;
  priority: Priority;
  actionRequired: string;
  timeToAction: number;
  estimatedImpact: string;
}

export interface EquipmentPerformanceTrend {
  trendId: string;
  equipmentId: string;
  parameter: string;
  trendDirection: string;
  strength: number;
  significance: number;
  forecast: Record<string, number>;
}

export interface DetectedMaintenanceAnomaly {
  anomalyId: string;
  equipmentId: string;
  anomalyType: string;
  severity: FailureSeverity;
  confidence: number;
  detectedAt: Date;
  description: string;
  recommendedActions: string[];
}

export interface PredictiveDiagnostics {
  diagnosticId: string;
  equipmentId: string;
  diagnosis: string;
  confidence: number;
  possibleCauses: string[];
  recommendedTests: string[];
  treatmentOptions: string[];
}

export interface MaintenanceMonitoringInsight {
  insightId: string;
  category: string;
  equipmentId: string;
  insight: string;
  impact: string;
  actionable: boolean;
  recommendations: string[];
}

export interface EquipmentPerformanceOptimization {
  optimizationId: string;
  equipmentId: string;
  optimizationTargets: string[];
  recommendations: string[];
  expectedImprovement: Record<string, number>;
  implementationPlan: string[];
}

export interface RealTimeIoTEquipmentMonitoringResult {
  monitoringId: string;
  monitoringTimestamp: Date;
  originalRequest: RealTimeIoTEquipmentMonitoringRequest;
  sensorNetworkDeployment: DeployedMaintenanceIoTNetwork;
  realTimeProcessing: ProcessedMaintenanceDataStream[];
  healthMonitoring: EquipmentHealthMetrics[];
  cbmTriggering: TriggeredMaintenanceActions[];
  trendAnalysis: EquipmentPerformanceTrend[];
  anomalyDetection: DetectedMaintenanceAnomaly[];
  predictiveDiagnostics: PredictiveDiagnostics[];
  monitoringInsights: MaintenanceMonitoringInsight[];
  performanceOptimization: EquipmentPerformanceOptimization;
}

// ===========================================
// ADDITIONAL REQUEST/RESPONSE TYPES
// ===========================================

// Placeholder interfaces for other complex operations
export interface AutonomousMaintenanceAgentRequest {
  diagnosticParameters: Record<string, any>;
  executionParameters: Record<string, any>;
  inspectionParameters: Record<string, any>;
  planningParameters: Record<string, any>;
  learningParameters: Record<string, any>;
  coordinationParameters: Record<string, any>;
}

export interface AutonomousMaintenanceAgentResult {
  agentId: string;
  deploymentTimestamp: Date;
  originalRequest: AutonomousMaintenanceAgentRequest;
  diagnosticAgents: any;
  executionAgents: any;
  inspectionAgents: any;
  planningAgents: any;
  learningAgents: any;
  coordinationNetwork: any;
  agentPerformance: any;
  agentOptimization: any;
  autonomousInsights: any;
}

export interface QuantumMaintenanceOptimizationRequest {
  schedulingParameters: Record<string, any>;
  resourceParameters: Record<string, any>;
  spaceParameters: Record<string, any>;
  patternParameters: Record<string, any>;
  processParameters: Record<string, any>;
}

export interface QuantumMaintenanceOptimizationResult {
  quantumId: string;
  quantumTimestamp: Date;
  originalRequest: QuantumMaintenanceOptimizationRequest;
  schedulingOptimization: any;
  resourceAllocation: any;
  spaceExploration: any;
  patternRecognition: any;
  processOptimization: any;
  quantumAdvantage: any;
  implementationGuidance: any;
}

// Additional request/response type placeholders for the comprehensive system
export interface ExtendedRealityMaintenanceRequest {
  arParameters: Record<string, any>;
  vrParameters: Record<string, any>;
  mrParameters: Record<string, any>;
  hapticParameters: Record<string, any>;
  gestureParameters: Record<string, any>;
  voiceParameters: Record<string, any>;
}

export interface ExtendedRealityMaintenanceResult {
  xrId: string;
  xrTimestamp: Date;
  originalRequest: ExtendedRealityMaintenanceRequest;
  arEquipmentVisualization: any;
  vrTrainingSimulations: any;
  mrCollaborativeMaintenance: any;
  hapticMaintenanceSystems: any;
  gestureMaintenanceControl: any;
  voiceMaintenanceCommands: any;
  xrPerformance: any;
  userExperience: any;
}

// More comprehensive request/response types would be defined here
// for all the other advanced systems referenced in the maintenance service
