import { OrganizationEntity } from './organization.entity';
import { DepartmentEntity } from './department.entity';
import { PositionEntity } from './position.entity';
import { EmployeeCompensationEntity } from './employee-compensation.entity';
import { PayrollRecordEntity } from './payroll-record.entity';
import { PerformanceReviewEntity } from './performance-review.entity';
export declare class EmployeeEntity {
    id: string;
    organizationId: string;
    employeeNumber: string;
    firstName: string;
    middleName: string;
    lastName: string;
    fullName: string;
    displayName: string;
    preferredName: string;
    workEmail: string;
    personalEmail: string;
    phoneNumber: string;
    mobileNumber: string;
    departmentId: string;
    positionId: string;
    jobTitle: string;
    jobCode: string;
    location: string;
    building: string;
    floor: string;
    workstation: string;
    employmentStatus: string;
    employmentType: string;
    hireDate: Date;
    startDate: Date;
    terminationDate: Date;
    terminationReason: string;
    probationEndDate: Date;
    isActive: boolean;
    isProbation: boolean;
    managerId: string;
    directReportsCount: number;
    dateOfBirth: Date;
    gender: string;
    nationality: string;
    maritalStatus: string;
    homeAddress: string;
    city: string;
    state: string;
    postalCode: string;
    country: string;
    baseSalary: number;
    currency: string;
    payGrade: string;
    payFrequency: string;
    bonusTargetPercentage: number;
    standardHoursPerWeek: number;
    workSchedule: string;
    timezone: string;
    emergencyContact: {
        name: string;
        relationship: string;
        phoneNumber: string;
        email?: string;
        address?: string;
    };
    skills: string[];
    languages: string[];
    certifications: string[];
    education: Array<{
        degree: string;
        institution: string;
        fieldOfStudy: string;
        graduationYear: number;
        gpa?: number;
    }>;
    profilePictureUrl: string;
    lastLoginAt: Date;
    badgeNumber: string;
    workstationId: string;
    socialSecurityNumber: string;
    nationalId: string;
    passportNumber: string;
    visaStatus: string;
    visaExpiryDate: Date;
    backgroundCheckCompleted: boolean;
    backgroundCheckDate: Date;
    lastPerformanceRating: number;
    lastPerformanceReviewDate: Date;
    nextPerformanceReviewDate: Date;
    goals: Array<{
        title: string;
        description: string;
        targetDate: string;
        status: string;
    }>;
    customFields: Record<string, any>;
    preferences: Record<string, any>;
    metadata: Record<string, any>;
    tags: string[];
    createdAt: Date;
    updatedAt: Date;
    organization: OrganizationEntity;
    department: DepartmentEntity;
    position: PositionEntity;
    manager: EmployeeEntity;
    directReports: EmployeeEntity[];
    compensations: EmployeeCompensationEntity[];
    payrollRecords: PayrollRecordEntity[];
    performanceReviews: PerformanceReviewEntity[];
    performanceReviewsAsReviewer: PerformanceReviewEntity[];
}
//# sourceMappingURL=employee.entity.d.ts.map