import { OrganizationEntity } from './organization.entity';
import { EmployeeEntity } from './employee.entity';
import { PayrollRecordEntity } from './payroll-record.entity';
export declare class PayrollRunEntity {
    id: string;
    organizationId: string;
    name: string;
    description: string;
    payPeriodStart: Date;
    payPeriodEnd: Date;
    payDate: Date;
    payrollFrequency: string;
    status: string;
    includeSalary: boolean;
    includeBonus: boolean;
    includeCommission: boolean;
    includeBenefits: boolean;
    includeDeductions: boolean;
    includeTaxes: boolean;
    includeOvertime: boolean;
    includeHolidayPay: boolean;
    employeeFilters: {
        departments?: string[];
        locations?: string[];
        employmentTypes?: string[];
        payGrades?: string[];
        managerIds?: string[];
        includeInactive?: boolean;
        customFilters?: Record<string, any>;
    };
    totalGrossPay: number;
    totalNetPay: number;
    totalDeductions: number;
    totalTaxes: number;
    totalBenefits: number;
    totalBonus: number;
    totalCommission: number;
    totalOvertime: number;
    currency: string;
    totalEmployees: number;
    processedEmployees: number;
    failedEmployees: number;
    skippedEmployees: number;
    processingStartedAt: Date;
    processingCompletedAt: Date;
    processedDate: Date;
    processingDurationSeconds: number;
    createdById: string;
    approvedById: string;
    approvedDate: Date;
    approvalNotes: string;
    paymentMethod: string;
    paymentBatchId: string;
    paymentDate: Date;
    paymentStatus: string;
    processingErrors: Array<{
        employeeId: string;
        employeeNumber: string;
        employeeName: string;
        errorCode: string;
        errorMessage: string;
        timestamp: string;
    }>;
    processingWarnings: Array<{
        type: string;
        message: string;
        employeeId?: string;
        timestamp: string;
    }>;
    taxYear: number;
    taxQuarter: number;
    taxMonth: number;
    taxPeriodType: string;
    isYearEndRun: boolean;
    isAdjustmentRun: boolean;
    isFinalRun: boolean;
    isTestRun: boolean;
    adjustmentReason: string;
    exportHistory: Array<{
        exportType: string;
        exportDate: string;
        fileName: string;
        recordCount: number;
        status: string;
    }>;
    integrationData: Record<string, any>;
    customDeductions: Array<{
        name: string;
        type: string;
        amount: number;
        isPercentage: boolean;
        applyToEmployees: string[];
    }>;
    customEarnings: Array<{
        name: string;
        type: string;
        amount: number;
        isPercentage: boolean;
        applyToEmployees: string[];
    }>;
    notes: string;
    processingNotes: string;
    settings: Record<string, any>;
    metadata: Record<string, any>;
    tags: string[];
    createdAt: Date;
    updatedAt: Date;
    organization: OrganizationEntity;
    createdBy: EmployeeEntity;
    approvedBy: EmployeeEntity;
    payrollRecords: PayrollRecordEntity[];
}
//# sourceMappingURL=payroll-run.entity.d.ts.map