import { OrganizationEntity } from './organization.entity';
import { EmployeeEntity } from './employee.entity';
import { PayrollRunEntity } from './payroll-run.entity';
export declare class PayrollRecordEntity {
    id: string;
    organizationId: string;
    employeeId: string;
    payrollRunId: string;
    payPeriodStart: Date;
    payPeriodEnd: Date;
    payDate: Date;
    payFrequency: string;
    employeeNumber: string;
    employeeName: string;
    jobTitle: string;
    department: string;
    location: string;
    payGrade: string;
    employmentType: string;
    employmentStatus: string;
    regularHours: number;
    overtimeHours: number;
    doubleTimeHours: number;
    holidayHours: number;
    sickHours: number;
    vacationHours: number;
    personalHours: number;
    totalHours: number;
    baseSalary: number;
    hourlyRate: number;
    overtimeRate: number;
    doubleTimeRate: number;
    currency: string;
    regularPay: number;
    overtimePay: number;
    doubleTimePay: number;
    holidayPay: number;
    bonusAmount: number;
    commissionAmount: number;
    allowancesAmount: number;
    reimbursementsAmount: number;
    grossPay: number;
    earningsDetails: Array<{
        type: string;
        description: string;
        hours?: number;
        rate?: number;
        amount: number;
        isTaxable: boolean;
        category: string;
    }>;
    federalIncomeTax: number;
    stateIncomeTax: number;
    localIncomeTax: number;
    socialSecurityTax: number;
    medicareeTax: number;
    unemploymentTax: number;
    disabilityTax: number;
    totalTaxes: number;
    healthInsurancePremium: number;
    dentalInsurancePremium: number;
    visionInsurancePremium: number;
    lifeInsurancePremium: number;
    disabilityInsurancePremium: number;
    retirement401kEmployee: number;
    retirement401kEmployer: number;
    totalBenefitDeductions: number;
    unionDues: number;
    garnishments: number;
    loanRepayments: number;
    otherDeductions: number;
    totalDeductions: number;
    deductionsDetails: Array<{
        type: string;
        description: string;
        amount: number;
        isPreTax: boolean;
        isEmployeeContribution: boolean;
        category: string;
    }>;
    netPay: number;
    takeHomePay: number;
    ytdGrossPay: number;
    ytdNetPay: number;
    ytdTaxes: number;
    ytdDeductions: number;
    ytdFederalTax: number;
    ytdStateTax: number;
    ytdSocialSecurityTax: number;
    ytdMedicareTax: number;
    ytdHours: number;
    paymentMethod: string;
    paymentReference: string;
    paymentStatus: string;
    paymentDate: Date;
    taxWithholdingInfo: {
        federalWithholding: {
            filingStatus: string;
            allowances: number;
            additionalAmount: number;
            exemptions: number;
        };
        stateWithholding: {
            filingStatus: string;
            allowances: number;
            additionalAmount: number;
        };
        localWithholding?: {
            rate: number;
            additionalAmount: number;
        };
    };
    isAdjustment: boolean;
    isFinalPay: boolean;
    isVoided: boolean;
    adjustmentReason: string;
    voidedDate: Date;
    voidReason: string;
    status: string;
    processingErrors: Array<{
        errorCode: string;
        errorMessage: string;
        timestamp: string;
    }>;
    notes: string;
    payrollNotes: string;
    customFields: Record<string, any>;
    metadata: Record<string, any>;
    tags: string[];
    createdAt: Date;
    updatedAt: Date;
    organization: OrganizationEntity;
    employee: EmployeeEntity;
    payrollRun: PayrollRunEntity;
}
//# sourceMappingURL=payroll-record.entity.d.ts.map