import { OrganizationEntity } from './organization.entity';
import { DepartmentEntity } from './department.entity';
import { EmployeeEntity } from './employee.entity';
export declare class PositionEntity {
    id: string;
    organizationId: string;
    departmentId: string;
    title: string;
    code: string;
    description: string;
    summary: string;
    responsibilities: string;
    requirements: string;
    qualifications: string;
    level: string;
    category: string;
    jobFamily: string;
    payGrade: string;
    employmentType: string;
    isRemoteEligible: boolean;
    isManagerialRole: boolean;
    requiresTravel: boolean;
    travelPercentage: number;
    maxOccupants: number;
    currentOccupants: number;
    isActive: boolean;
    isApproved: boolean;
    approvedDate: Date;
    reportsToPositionId: string;
    directReports: number;
    salaryMin: number;
    salaryMax: number;
    salaryMidpoint: number;
    salaryCurrency: string;
    bonusTargetPercentage: number;
    requiredSkills: string[];
    preferredSkills: string[];
    competencies: Record<string, any>;
    minimumEducation: string;
    minimumExperienceYears: number;
    preferredExperienceYears: number;
    certifications: string[];
    workLocation: string;
    workSchedule: string;
    physicalRequirements: string;
    workEnvironment: string;
    createdById: string;
    approvedById: string;
    status: string;
    benefits: Record<string, any>;
    settings: Record<string, any>;
    metadata: Record<string, any>;
    tags: string[];
    createdAt: Date;
    updatedAt: Date;
    organization: OrganizationEntity;
    department: DepartmentEntity;
    reportsToPosition: PositionEntity;
    subordinatePositions: PositionEntity[];
    employees: EmployeeEntity[];
    createdBy: EmployeeEntity;
    approvedBy: EmployeeEntity;
}
//# sourceMappingURL=position.entity.d.ts.map