export declare enum HRErrorCodes {
    EMPLOYEE_NOT_FOUND = "EMPLOYEE_NOT_FOUND",
    INVALID_EMPLOYEE_DATA = "INVALID_EMPLOYEE_DATA",
    DUPLICATE_EMPLOYEE_EMAIL = "DUPLICATE_EMPLOYEE_EMAIL",
    INVALID_MANAGER_ASSIGNMENT = "INVALID_MANAGER_ASSIGNMENT",
    EMPLOYEE_HIERARCHY_LOOP = "EMPLOYEE_HIERARCHY_LOOP",
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS",
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
    INVALID_TOKEN = "INVALID_TOKEN",
    REQUISITION_NOT_FOUND = "REQUISITION_NOT_FOUND",
    INVALID_REQUISITION_DATA = "INVALID_REQUISITION_DATA",
    INVALID_JOB_REQUISITION_DATA = "INVALID_JOB_REQUISITION_DATA",
    REQUISITION_ALREADY_FILLED = "REQUISITION_ALREADY_FILLED",
    APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND",
    INVALID_APPLICATION_DATA = "INVALID_APPLICATION_DATA",
    APPLICATION_ALREADY_EXISTS = "APPLICATION_ALREADY_EXISTS",
    INVALID_APPLICATION_STATUS_TRANSITION = "INVALID_APPLICATION_STATUS_TRANSITION",
    CANDIDATE_NOT_FOUND = "CANDIDATE_NOT_FOUND",
    INVALID_CANDIDATE_DATA = "INVALID_CANDIDATE_DATA",
    DUPLICATE_CANDIDATE_EMAIL = "DUPLICATE_CANDIDATE_EMAIL",
    INTERVIEW_NOT_FOUND = "INTERVIEW_NOT_FOUND",
    INTERVIEW_SCHEDULING_CONFLICT = "INTERVIEW_SCHEDULING_CONFLICT",
    INVALID_INTERVIEW_DATA = "INVALID_INTERVIEW_DATA",
    INTERVIEWER_NOT_AVAILABLE = "INTERVIEWER_NOT_AVAILABLE",
    PERFORMANCE_REVIEW_NOT_FOUND = "PERFORMANCE_REVIEW_NOT_FOUND",
    INVALID_PERFORMANCE_REVIEW_DATA = "INVALID_PERFORMANCE_REVIEW_DATA",
    INVALID_PERFORMANCE_DATA = "INVALID_PERFORMANCE_DATA",
    REVIEW_PERIOD_OVERLAP = "REVIEW_PERIOD_OVERLAP",
    COMPETENCY_NOT_FOUND = "COMPETENCY_NOT_FOUND",
    COMPENSATION_PLAN_NOT_FOUND = "COMPENSATION_PLAN_NOT_FOUND",
    COMPENSATION_PLAN_ALREADY_EXISTS = "COMPENSATION_PLAN_ALREADY_EXISTS",
    SALARY_STRUCTURE_NOT_FOUND = "SALARY_STRUCTURE_NOT_FOUND",
    SALARY_STRUCTURE_OVERLAP = "SALARY_STRUCTURE_OVERLAP",
    INVALID_COMPENSATION_DATA = "INVALID_COMPENSATION_DATA",
    BENEFIT_PLAN_NOT_FOUND = "BENEFIT_PLAN_NOT_FOUND",
    BENEFITS_PLAN_NOT_FOUND = "BENEFITS_PLAN_NOT_FOUND",
    BENEFITS_PLAN_ALREADY_EXISTS = "BENEFITS_PLAN_ALREADY_EXISTS",
    BENEFITS_ENROLLMENT_NOT_FOUND = "BENEFITS_ENROLLMENT_NOT_FOUND",
    BENEFITS_ENROLLMENT_EXISTS = "BENEFITS_ENROLLMENT_EXISTS",
    BENEFITS_ENROLLMENT_NOT_ELIGIBLE = "BENEFITS_ENROLLMENT_NOT_ELIGIBLE",
    PAYROLL_PERIOD_NOT_FOUND = "PAYROLL_PERIOD_NOT_FOUND",
    PAYROLL_RUN_NOT_FOUND = "PAYROLL_RUN_NOT_FOUND",
    PAYROLL_PERIOD_OVERLAP = "PAYROLL_PERIOD_OVERLAP",
    INVALID_PAYROLL_STATUS = "INVALID_PAYROLL_STATUS",
    INVALID_PAYROLL_DATA = "INVALID_PAYROLL_DATA",
    INVALID_TIME_ENTRY = "INVALID_TIME_ENTRY",
    TIME_ENTRY_CONFLICT = "TIME_ENTRY_CONFLICT",
    LEAVE_REQUEST_NOT_FOUND = "LEAVE_REQUEST_NOT_FOUND",
    INSUFFICIENT_LEAVE_BALANCE = "INSUFFICIENT_LEAVE_BALANCE",
    ALREADY_CLOCKED_IN = "ALREADY_CLOCKED_IN",
    NOT_CLOCKED_IN = "NOT_CLOCKED_IN",
    LEAVE_REQUEST_OVERLAP = "LEAVE_REQUEST_OVERLAP",
    INVALID_LEAVE_REQUEST = "INVALID_LEAVE_REQUEST",
    TRAINING_PROGRAM_NOT_FOUND = "TRAINING_PROGRAM_NOT_FOUND",
    ENROLLMENT_NOT_FOUND = "ENROLLMENT_NOT_FOUND",
    PREREQUISITE_NOT_MET = "PREREQUISITE_NOT_MET",
    TRAINING_CAPACITY_EXCEEDED = "TRAINING_CAPACITY_EXCEEDED",
    EXIT_RECORD_NOT_FOUND = "EXIT_RECORD_NOT_FOUND",
    INVALID_EXIT_DATA = "INVALID_EXIT_DATA",
    INVALID_EXIT_INTERVIEW_DATA = "INVALID_EXIT_INTERVIEW_DATA",
    EXIT_INTERVIEW_NOT_FOUND = "EXIT_INTERVIEW_NOT_FOUND",
    OFFBOARDING_CHECKLIST_NOT_FOUND = "OFFBOARDING_CHECKLIST_NOT_FOUND",
    KNOWLEDGE_TRANSFER_PLAN_NOT_FOUND = "KNOWLEDGE_TRANSFER_PLAN_NOT_FOUND",
    DATABASE_ERROR = "DATABASE_ERROR",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR",
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
    FILE_UPLOAD_ERROR = "FILE_UPLOAD_ERROR",
    AI_PROCESSING_ERROR = "AI_PROCESSING_ERROR",
    INSUFFICIENT_DATA_FOR_ANALYSIS = "INSUFFICIENT_DATA_FOR_ANALYSIS",
    MODEL_NOT_AVAILABLE = "MODEL_NOT_AVAILABLE"
}
export declare class HRError extends Error {
    readonly code: HRErrorCodes;
    readonly statusCode: number;
    readonly details?: Record<string, any>;
    readonly timestamp: Date;
    constructor(code: HRErrorCodes, message: string, statusCode?: number, details?: Record<string, any>);
    /**
     * Convert the error to a JSON object for API responses
     */
    toJSON(): Record<string, any>;
    /**
     * Check if this error is a specific type
     */
    isOfType(code: HRErrorCodes): boolean;
    /**
     * Create a user-friendly error message
     */
    getUserMessage(): string;
}
/**
 * Factory functions for common HR errors
 */
export declare class HRErrorFactory {
    static employeeNotFound(employeeId: string, details?: Record<string, any>): HRError;
    static duplicateEmployeeEmail(email: string, details?: Record<string, any>): HRError;
    static unauthorizedAccess(action: string, resource: string, details?: Record<string, any>): HRError;
    static validationError(field: string, message: string, details?: Record<string, any>): HRError;
    static databaseError(operation: string, tableName: string, details?: Record<string, any>): HRError;
    static requisitionNotFound(requisitionId: string, details?: Record<string, any>): HRError;
    static applicationNotFound(applicationId: string, details?: Record<string, any>): HRError;
    static interviewSchedulingConflict(interviewerId: string, scheduledTime: Date, details?: Record<string, any>): HRError;
}
/**
 * Error handler middleware helper
 */
export declare function handleHRError(error: any): HRError;
/**
 * Error response formatter for API responses
 */
export declare function formatErrorResponse(error: HRError): {
    success: boolean;
    error: {
        code: HRErrorCodes;
        message: string;
        details: Record<string, any> | undefined;
        timestamp: string;
    };
};
//# sourceMappingURL=error.util.d.ts.map