import { Repository } from 'typeorm';
import { Cybersecurity } from '../entities/Cybersecurity';
import { CreateCybersecurityDto } from '../dto/create-cybersecurity.dto';
import { UpdateCybersecurityDto } from '../dto/update-cybersecurity.dto';
import { CybersecurityResponseDto } from '../dto/cybersecurity-response.dto';
import { PaginationDto } from '../../../common/dto/pagination.dto';
export declare class CybersecurityService {
    private readonly cybersecurityRepository;
    private readonly logger;
    constructor(cybersecurityRepository: Repository<Cybersecurity>);
    create(createCybersecurityDto: CreateCybersecurityDto): Promise<CybersecurityResponseDto>;
    findAll(paginationDto: PaginationDto, filters: {
        search?: string;
        securityLevel?: string;
        threatLevel?: string;
        complianceFramework?: string;
    }): Promise<{
        data: CybersecurityResponseDto[];
        total: number;
        page: number;
        limit: number;
    }>;
    findOne(id: string): Promise<CybersecurityResponseDto>;
    update(id: string, updateCybersecurityDto: UpdateCybersecurityDto): Promise<CybersecurityResponseDto>;
    remove(id: string): Promise<void>;
    getSecurityScore(id: string): Promise<any>;
    detectThreat(id: string, threatData: any): Promise<any>;
    createIncident(id: string, incidentData: any): Promise<any>;
    respondToIncident(id: string, incidentId: string, responseAction: any): Promise<any>;
    runVulnerabilityAssessment(id: string): Promise<any>;
    enableQuantumSecurity(id: string): Promise<any>;
    enableBlockchainSecurity(id: string): Promise<any>;
    conductSecurityTraining(id: string, trainingType: string, participants: string[]): Promise<any>;
    getComplianceScore(id: string): Promise<any>;
    generateSecurityReport(id: string): Promise<any>;
    auditSecurity(id: string, auditorId: string): Promise<any>;
    updateSecurityMetrics(id: string, metricsData: any): Promise<any>;
    getActiveThreats(id: string): Promise<any>;
    getSecurityAnalytics(id: string, period?: string): Promise<any>;
    initiateEmergencyResponse(id: string, emergencyData: any): Promise<any>;
    clone(id: string, cloneData: {
        newSecurityCode: string;
        newSecurityName: string;
    }): Promise<CybersecurityResponseDto>;
    getRiskAssessment(id: string): Promise<any>;
    getSecurityCulture(id: string): Promise<any>;
    private mapToResponseDto;
    private getSecurityAssessment;
    private getScoreBreakdown;
    private generateThreatResponse;
    private generateThreatRecommendations;
    private getIncidentRecommendations;
    private getNextSteps;
    private createActionPlan;
    private prioritizeVulnerabilities;
    private getQuantumSecurityBenefits;
    private getQuantumImplementationSteps;
    private getBlockchainSecurityBenefits;
    private getBlockchainImplementationSteps;
    private getTrainingFollowUp;
    private getComplianceStatus;
    private identifyComplianceGaps;
    private getComplianceRecommendations;
    private generateExecutiveSummary;
    private extractActionItems;
    private createRemediationPlan;
    private createAuditTimeline;
    private getMetricsRecommendations;
    private createThreatSummary;
    private calculateSecurityTrends;
    private getSecurityBenchmarks;
    private generateSecurityInsights;
    private generateSecurityPredictions;
    private getImmediateActions;
    private getShortTermActions;
    private getLongTermActions;
    private getContainmentMeasures;
    private getCommunicationPlan;
    private createRiskMatrix;
    private getRiskMitigationRecommendations;
    private createRiskTimeline;
    private assessSecurityMaturity;
    private getSecurityCultureImprovements;
}
//# sourceMappingURL=cybersecurity.service.d.ts.map