import { CycleCountStatus } from '../enums';
import { InventoryItem } from './InventoryItem';
export declare class CycleCount {
    id: string;
    itemId: string;
    locationCode?: string;
    status: CycleCountStatus;
    expectedQuantity: number;
    actualQuantity?: number;
    variance: number;
    variancePercentage: number;
    scheduledDate?: Date;
    startedAt?: Date;
    completedAt?: Date;
    createdBy: string;
    countedBy?: string;
    completedBy?: string;
    approvedBy?: string;
    notes?: string;
    countType?: string;
    countSequence: number;
    countReason?: string;
    batchNumber?: string;
    serialNumber?: string;
    expiryDate?: Date;
    unitCost?: number;
    varianceValue?: number;
    countMethod?: string;
    deviceUsed?: string;
    countDetails?: {
        temperature?: number;
        humidity?: number;
        conditions?: string;
        photos?: string[];
        witnesses?: string[];
    };
    requiresRecount: boolean;
    isRecounted: boolean;
    recountReason?: string;
    countAttempt: number;
    createdAt: Date;
    updatedAt: Date;
    item: InventoryItem;
    calculateVariance(): void;
    isPending(): boolean;
    isInProgress(): boolean;
    isCompleted(): boolean;
    isCancelled(): boolean;
    hasVariance(): boolean;
    hasPositiveVariance(): boolean;
    hasNegativeVariance(): boolean;
    isSignificantVariance(threshold?: number): boolean;
    getDaysOverdue(): number;
    isOverdue(): boolean;
    getCountDuration(): number | null;
    getVarianceSeverity(): 'NONE' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    getPriority(): 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
    canBeCompleted(): boolean;
    canBeCancelled(): boolean;
    needsApproval(): boolean;
    complete(actualQuantity: number, countedBy: string, notes?: string): void;
    start(countedBy: string): void;
    cancel(reason?: string): void;
    approve(approvedBy: string): void;
    scheduleRecount(reason: string): void;
    toJSON(): {
        id: string;
        itemId: string;
        locationCode: string | undefined;
        status: CycleCountStatus;
        expectedQuantity: number;
        actualQuantity: number | undefined;
        variance: number;
        variancePercentage: number;
        varianceValue: number | undefined;
        scheduledDate: Date | undefined;
        startedAt: Date | undefined;
        completedAt: Date | undefined;
        createdBy: string;
        countedBy: string | undefined;
        completedBy: string | undefined;
        approvedBy: string | undefined;
        notes: string | undefined;
        countType: string | undefined;
        countSequence: number;
        countReason: string | undefined;
        batchNumber: string | undefined;
        serialNumber: string | undefined;
        expiryDate: Date | undefined;
        countMethod: string | undefined;
        deviceUsed: string | undefined;
        countDetails: {
            temperature?: number;
            humidity?: number;
            conditions?: string;
            photos?: string[];
            witnesses?: string[];
        } | undefined;
        requiresRecount: boolean;
        isRecounted: boolean;
        recountReason: string | undefined;
        countAttempt: number;
        hasVariance: boolean;
        hasPositiveVariance: boolean;
        hasNegativeVariance: boolean;
        varianceSeverity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | "NONE";
        priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
        isOverdue: boolean;
        daysOverdue: number;
        countDuration: number | null;
        needsApproval: boolean;
        canBeCompleted: boolean;
        canBeCancelled: boolean;
        createdAt: Date;
        updatedAt: Date;
    };
}
//# sourceMappingURL=CycleCount.d.ts.map