import { AlertType, AlertSeverity, AlertStatus } from '../enums';
import { InventoryItem } from './InventoryItem';
export declare class InventoryAlert {
    id: string;
    itemId?: string;
    type: AlertType;
    severity: AlertSeverity;
    status: AlertStatus;
    title: string;
    description: string;
    recommendation?: string;
    threshold?: number;
    currentValue?: number;
    locationCode?: string;
    warehouseCode?: string;
    category?: string;
    alertData?: {
        originalQuantity?: number;
        currentQuantity?: number;
        reorderPoint?: number;
        maxStock?: number;
        leadTime?: number;
        demandRate?: number;
        costImpact?: number;
        affectedLocations?: string[];
        relatedItems?: string[];
        seasonalFactor?: number;
        forecastAccuracy?: number;
    };
    alertConditions?: {
        triggerCondition?: string;
        thresholdOperator?: 'GT' | 'LT' | 'EQ' | 'GTE' | 'LTE';
        comparisonValue?: number;
        timeWindow?: number;
        frequency?: string;
        businessRules?: string[];
    };
    triggeredBy?: string;
    assignedTo?: string;
    resolvedBy?: string;
    resolvedAt?: Date;
    resolutionNotes?: string;
    resolutionAction?: string;
    isActive: boolean;
    isSystemGenerated: boolean;
    requiresImmedateAction: boolean;
    isEscalated: boolean;
    escalatedAt?: Date;
    escalatedTo?: string;
    escalationLevel?: string;
    dueDate?: Date;
    reminderCount: number;
    lastReminderSent?: Date;
    notificationChannels?: {
        email?: boolean;
        sms?: boolean;
        dashboard?: boolean;
        webhook?: boolean;
        slack?: boolean;
    };
    notificationHistory?: Array<{
        timestamp: Date;
        channel: string;
        recipient: string;
        status: 'sent' | 'delivered' | 'failed';
        message?: string;
    }>;
    businessImpact?: string;
    estimatedCostImpact?: number;
    department?: string;
    costCenter?: string;
    project?: string;
    occurrenceCount: number;
    firstOccurrence?: Date;
    lastOccurrence?: Date;
    createdAt: Date;
    updatedAt: Date;
    item?: InventoryItem;
    calculateMetrics(): void;
    acknowledge(userId: string): void;
    resolve(userId: string, notes?: string, action?: string): void;
    dismiss(userId: string, reason?: string): void;
    escalate(toUser: string, level?: string): void;
    snooze(hours: number): void;
    reactivate(): void;
    isOverdue(): boolean;
    isResolved(): boolean;
    isDismissed(): boolean;
    isAcknowledged(): boolean;
    isSnoozed(): boolean;
    canBeResolved(): boolean;
    canBeEscalated(): boolean;
    getAge(): number;
    getAgeInHours(): number;
    getAgeInDays(): number;
    getTimeToResolve(): number | null;
    needsReminder(): boolean;
    private getReminderInterval;
    sendReminder(): void;
    private calculateBusinessImpact;
    private calculateDueDate;
    private shouldRequireImmediateAction;
    getAlertTypeDescription(): string;
    getSeverityColor(): string;
    getPriorityScore(): number;
    toJSON(): {
        id: string;
        itemId: string | undefined;
        type: AlertType;
        typeDescription: string;
        severity: AlertSeverity;
        severityColor: string;
        status: AlertStatus;
        title: string;
        description: string;
        recommendation: string | undefined;
        threshold: number | undefined;
        currentValue: number | undefined;
        locationCode: string | undefined;
        warehouseCode: string | undefined;
        category: string | undefined;
        alertData: {
            originalQuantity?: number;
            currentQuantity?: number;
            reorderPoint?: number;
            maxStock?: number;
            leadTime?: number;
            demandRate?: number;
            costImpact?: number;
            affectedLocations?: string[];
            relatedItems?: string[];
            seasonalFactor?: number;
            forecastAccuracy?: number;
        } | undefined;
        alertConditions: {
            triggerCondition?: string;
            thresholdOperator?: "GT" | "LT" | "EQ" | "GTE" | "LTE";
            comparisonValue?: number;
            timeWindow?: number;
            frequency?: string;
            businessRules?: string[];
        } | undefined;
        triggeredBy: string | undefined;
        assignedTo: string | undefined;
        resolvedBy: string | undefined;
        resolvedAt: Date | undefined;
        resolutionNotes: string | undefined;
        resolutionAction: string | undefined;
        isActive: boolean;
        isSystemGenerated: boolean;
        requiresImmedateAction: boolean;
        isEscalated: boolean;
        escalatedAt: Date | undefined;
        escalatedTo: string | undefined;
        escalationLevel: string | undefined;
        dueDate: Date | undefined;
        reminderCount: number;
        lastReminderSent: Date | undefined;
        notificationChannels: {
            email?: boolean;
            sms?: boolean;
            dashboard?: boolean;
            webhook?: boolean;
            slack?: boolean;
        } | undefined;
        businessImpact: string | undefined;
        estimatedCostImpact: number | undefined;
        department: string | undefined;
        costCenter: string | undefined;
        project: string | undefined;
        occurrenceCount: number;
        firstOccurrence: Date | undefined;
        lastOccurrence: Date | undefined;
        age: number;
        ageInHours: number;
        ageInDays: number;
        isOverdue: boolean;
        needsReminder: boolean;
        canBeResolved: boolean;
        canBeEscalated: boolean;
        priorityScore: number;
        timeToResolve: number | null;
        createdAt: Date;
        updatedAt: Date;
    };
}
//# sourceMappingURL=InventoryAlert.d.ts.map