import { AdjustmentReason } from '../enums';
import { InventoryItem } from './InventoryItem';
export declare class InventoryAdjustment {
    id: string;
    itemId: string;
    adjustmentQuantity: number;
    quantityBefore: number;
    quantityAfter: number;
    reason: AdjustmentReason;
    notes?: string;
    referenceId?: string;
    documentNumber?: string;
    performedBy: string;
    approvedBy?: string;
    approvedAt?: Date;
    locationCode?: string;
    batchNumber?: string;
    serialNumber?: string;
    unitCost?: number;
    adjustmentValue?: number;
    adjustmentMethod?: string;
    sourceTransaction?: string;
    adjustmentDetails?: {
        beforePhoto?: string;
        afterPhoto?: string;
        witnesses?: string[];
        conditions?: string;
        equipment?: string;
        environment?: {
            temperature?: number;
            humidity?: number;
        };
    };
    requiresApproval: boolean;
    isApproved: boolean;
    isSystemGenerated: boolean;
    costCenter?: string;
    department?: string;
    project?: string;
    variancePercentage?: number;
    createdAt: Date;
    item: InventoryItem;
    calculateValues(): void;
    isPositiveAdjustment(): boolean;
    isNegativeAdjustment(): boolean;
    isZeroAdjustment(): boolean;
    getAdjustmentType(): 'INCREASE' | 'DECREASE' | 'NO_CHANGE';
    getAbsoluteAdjustment(): number;
    getAdjustmentValue(): number;
    getAbsoluteAdjustmentValue(): number;
    isSignificantAdjustment(threshold?: number): boolean;
    isLargeValueAdjustment(threshold?: number): boolean;
    shouldRequireApproval(): boolean;
    canBeApproved(): boolean;
    isPendingApproval(): boolean;
    approve(approvedBy: string): void;
    getReasonDescription(): string;
    getAdjustmentSummary(): string;
    getPriority(): 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    requiresInvestigation(): boolean;
    getFinancialImpact(): 'POSITIVE' | 'NEGATIVE' | 'NEUTRAL';
    toJSON(): {
        id: string;
        itemId: string;
        adjustmentQuantity: number;
        quantityBefore: number;
        quantityAfter: number;
        reason: AdjustmentReason;
        reasonDescription: string;
        notes: string | undefined;
        referenceId: string | undefined;
        documentNumber: string | undefined;
        performedBy: string;
        approvedBy: string | undefined;
        approvedAt: Date | undefined;
        locationCode: string | undefined;
        batchNumber: string | undefined;
        serialNumber: string | undefined;
        unitCost: number | undefined;
        adjustmentValue: number | undefined;
        adjustmentMethod: string | undefined;
        sourceTransaction: string | undefined;
        adjustmentDetails: {
            beforePhoto?: string;
            afterPhoto?: string;
            witnesses?: string[];
            conditions?: string;
            equipment?: string;
            environment?: {
                temperature?: number;
                humidity?: number;
            };
        } | undefined;
        requiresApproval: boolean;
        isApproved: boolean;
        isSystemGenerated: boolean;
        costCenter: string | undefined;
        department: string | undefined;
        project: string | undefined;
        variancePercentage: number | undefined;
        adjustmentType: "INCREASE" | "DECREASE" | "NO_CHANGE";
        absoluteAdjustment: number;
        absoluteAdjustmentValue: number;
        isSignificant: boolean;
        isLargeValue: boolean;
        priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        requiresInvestigation: boolean;
        financialImpact: "POSITIVE" | "NEGATIVE" | "NEUTRAL";
        adjustmentSummary: string;
        canBeApproved: boolean;
        isPendingApproval: boolean;
        createdAt: Date;
    };
}
//# sourceMappingURL=InventoryAdjustment.d.ts.map