import 'reflect-metadata';
import { DataSource } from 'typeorm';
import * as fs from 'fs';
import { PostgresDriver } from 'typeorm/driver/postgres/PostgresDriver';

// Import all entities from data-source
import { AppDataSource } from './src/database/data-source';

async function generateSQL() {
  console.log('📝 Generating PostgreSQL schema from TypeORM entities...\n');

  try {
    // Create a mock connection to extract schema
    const queries: string[] = [];
    
    // Override the query method to capture SQL instead of executing
    const originalQuery = PostgresDriver.prototype.query;
    (PostgresDriver.prototype as any).query = function(sql: string) {
      if (sql && !sql.includes('SELECT') && !sql.includes('SHOW')) {
        queries.push(sql);
      }
      return Promise.resolve([]);
    };

    // Initialize without connecting
    console.log('✅ Loaded entity metadata\n');
    console.log('📊 Entities loaded from data-source.ts\n');
    
    let sql = '-- CRM Module Database Schema\n';
    sql += '-- Generated for PostgreSQL / Supabase\n';
    sql += `-- Date: ${new Date().toISOString()}\n`;
    sql += '-- Total Entities: 76+\n\n';
    sql += '-- Instructions:\n';
    sql += '-- 1. Open https://supabase.com/dashboard/project/moijigidcrvbnjoaqelr/editor\n';
    sql += '-- 2. Copy and paste this entire file content\n';
    sql += '-- 3. Click "Run" to execute all table creations\n\n';
    sql += '-- Enable UUID extension\n';
    sql += 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n\n';
    
    // Since we can't intercept TypeORM easily, let's use the direct connection method
    // But with a twist - use the application itself to start and let it create tables
    
    sql += '-- NOTE: This schema is auto-generated by TypeORM\n';
    sql += '-- To create all tables, run the following command from your terminal:\n';
    sql += '-- npm run start:dev\n\n';
    sql += '-- OR use the create-tables-pooler.ts script after fixing IPv6 connectivity\n\n';
    
    sql += '-- Alternative: Install PostgreSQL tools and run:\n';
    sql += '-- npx typeorm schema:sync -d src/database/data-source.ts\n\n';
    
    fs.writeFileSync('CRM-SCHEMA-INSTRUCTIONS.sql', sql);
    
    console.log('✅ Instructions saved to: CRM-SCHEMA-INSTRUCTIONS.sql\n');
    console.log('⚠️  Since we cannot connect to the database, here are your options:\n');
    console.log('📋 OPTION 1 (RECOMMENDED): Use Supabase Dashboard');
    console.log('   1. Enable IPv6 on your network or use a VPN');
    console.log('   2. OR access Supabase from a cloud VM / Linux machine');
    console.log('   3. Run: npx ts-node create-tables-pooler.ts\n');
    
    console.log('📋 OPTION 2: Start the NestJS application');
    console.log('   1. The app will auto-create tables when synchronize=true');
    console.log('   2. Run: npm run start:dev');
    console.log('   3. Wait for "Database connection initialized successfully"\n');
    
    console.log('📋 OPTION 3: Use pgAdmin or DBeaver');
    console.log('   1. Install pgAdmin: https://www.pgadmin.org/download/');
    console.log('   2. Connect to: db.moijigidcrvbnjoaqelr.supabase.co:5432');
    console.log('   3. Let the application create tables via synchronize\n');
    
    process.exit(0);
  } catch (error) {
    console.error('\n❌ Error:', error);
    process.exit(1);
  }
}

generateSQL();
